### ISSUE TITLE
SDL crashed on Darwin: uncaught exception

### ISSUE THREAD

**Issue by zyxar** [zyxar/media-muxer#1]
same as https://github.com/banthar/Go-SDL/issues/64

2015-05-28 21:56:21.409 media-muxer[91061:507] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error (1000) creating CGSWindow on line 263'
*** First throw call stack:
(
  0   CoreFoundation                      0x00007fff8d68b25c __exceptionPreprocess + 172
  1   libobjc.A.dylib                     0x00007fff91f50e75 objc_exception_throw + 43
  2   CoreFoundation                      0x00007fff8d68b10c +[NSException raise:format:] + 204
  3   AppKit                              0x00007fff939fce95 _NSCreateWindowWithOpaqueShape2 + 1403
  4   AppKit                              0x00007fff939fba21 -[NSWindow _commonAwake] + 3720
  5   AppKit                              0x00007fff938d7400 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 882
  6   AppKit                              0x00007fff938d6882 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1054
  7   AppKit                              0x00007fff938d6458 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
  8   libSDL-1.2.0.dylib                  0x00000000042310f4 -[SDL_QuartzWindow initWithContentRect:styleMask:backing:defer:] + 279
  9   libSDL-1.2.0.dylib                  0x000000000422ea6a QZ_SetVideoMode + 1172
  10  libSDL-1.2.0.dylib                  0x0000000004225dfa SDL_SetVideoMode + 907
  11  media-muxer                         0x0000000004001b65 _cgo_3918b09afbb6_Cfunc_SDL_SetVideoMode + 37
  12  media-muxer                         0x0000000004038ed5 asmcgocall + 101
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff94421866
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001b40, 0xc20801d5b8, 0x0)
  /usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc20801d598 sp=0xc20801d570
_/Users/x/Desktop/arbeits/media-muxer/mux._Cfunc_SDL_SetVideoMode(0x2d000000500, 0x0, 0x0)
  /Users/x/Desktop/arbeits/media-muxer/mux/:84 +0x44 fp=0xc20801d5b8 sp=0xc20801d598
_/Users/x/Desktop/arbeits/media-muxer/mux.NewDisplay(0x4117300, 0x6, 0x500, 0x2d0, 0x0, 0x0, 0x0)
  /Users/x/Desktop/arbeits/media-muxer/mux/display.go:27 +0xda fp=0xc20801d618 sp=0xc20801d5b8
_/Users/x/Desktop/arbeits/media-muxer/mux.NewMuxer(0x0, 0x0, 0x7fff5fbff83e, 0x5, 0x0, 0x0, 0x0)
  /Users/x/Desktop/arbeits/media-muxer/mux/muxer.go:122 +0x3d8 fp=0xc20801d6d8 sp=0xc20801d618
main.main()
  /Users/x/Desktop/arbeits/media-muxer/main.go:28 +0x308 fp=0xc20801d798 sp=0xc20801d6d8
runtime.main()
  /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:63 +0xf3 fp=0xc20801d7e0 sp=0xc20801d798
runtime.goexit()
  /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
  /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x7fff7b296310
rcx     0x7fff5fbfda68
rdx     0x0
rdi     0x507
rsi     0x6
rbp     0x7fff5fbfda90
rsp     0x7fff5fbfda68
r8      0x6e6f697470656378
r9      0x7fff8a7a28d0
r10     0x8000000
r11     0x206
r12     0x7fff5fbfdbf0
r13     0x6b1c928
r14     0x6
r15     0x7fff5fbfdad0
rip     0x7fff94421866
rflags  0x206
cs      0x7
fs      0x0
gs      0x6af0000

**Comment by zyxar** [comment]
it works on OS X Yosemite.
